A non-smoke test version of the end-to-end test
opensafely-core/cohort-extractor-v2 pull request #26
Opened 2021-07-07 17:12 UTC by rebkwok

2021-07-09 16:11 UTC, benbc requested changes
I feel like there must be a slightly cleaner way of doing this. At the moment the understanding about how to handle the two different ways of running the extraction is spread out between the test functions (where `method` and `args` are specified) and `run_test()` (where the logic for the results is).

Could we instead pass in a "runner" callable that takes care of both aspects? Something a bit like this (not checked it properly):

```
def test_extracts_data_from_sql_server_integration_tests(load_study, load data, database):
    study = load_study("end_to_end_tests")
    
    def runner():
        main(str(study.path), "mock", database.host_url())
        return study.path / "outputs
        
    run_test(study, load_data, runner)
```

2021-07-09 16:29 UTC, rebkwok commented on tests/test_end_to_end.py
> +    ) == expected_results.read_text(encoding="utf-8")
Maybe it's useful if/when the output files get more complex. I can change it back if you prefer

2021-07-09 16:49 UTC, rebkwok commented on tests/conftest.py
> +        shutil.rmtree(output_dir)
The temporary directory is only created in the container.  When main is called directly, it uses the fixtures folder.  I'll try making it also use the copying-to-temp-dir

2021-07-09 17:25 UTC, rebkwok commented on tests/conftest.py
> +        shutil.rmtree(output_dir)
Done.  Not sure if I prefer it this way more or not

2021-07-12 12:10 UTC, benbc approved these changes

2021-07-12 13:02 UTC, merged